// AUTO-GENERATED by scripts/gen-edge-fingerprint.mjs — DO NOT EDIT.
// sha256 (first 12 hex) over the chat-turn import graph (57 files,
// walked from index.ts incl. the ../../../src legal/type modules the deploy
// bundler ships). Served by the GET health probe; compared against the local
// tree by `npm run verify:deploy` (edge rail). Regenerate:
//   node scripts/gen-edge-fingerprint.mjs
export const EDGE_FINGERPRINT = 'ce041cbf1d71'
export const EDGE_FINGERPRINT_FILES = 57
